## Import

In [18]:
import cv2
import numpy as np

## Images

#### Read Image as Array

In [2]:
# 0: Greyscale, 1: BGR
img = cv2.imread("data/smallgray.png",0)

In [3]:
img

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [4]:
img_color = cv2.imread("data/smallgray.png", 1)

In [5]:
img_color

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

#### Write Array as Image

In [6]:
cv2.imwrite("newsmallgrey.png", img)

True

## NP Operations

#### Slice / Access

In [12]:
# Row indexes, column indexes
img[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [13]:
img[:,2:]

array([[104, 121, 143],
       [255, 255, 147],
       [255,  97, 182]], dtype=uint8)

#### Iterate

In [15]:
# Iterate rows
for i in img:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [16]:
# Iterate columns
for i in img.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [17]:
# Flat iterate
for i in img.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


#### Stacking and Splitting

In [27]:
# Horizontal Stack
h_stack = np.hstack((img,img))

In [28]:
h_stack

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [29]:
# Vertical Stack
v_stack = np.vstack((img,img))

In [30]:
v_stack

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [31]:
# Split
v_split = np.vsplit(img, 3)

In [32]:
v_split

[array([[187, 158, 104, 121, 143]], dtype=uint8),
 array([[198, 125, 255, 255, 147]], dtype=uint8),
 array([[209, 134, 255,  97, 182]], dtype=uint8)]

In [34]:
h_split = np.hsplit(img, 5)

In [35]:
h_split

[array([[187],
        [198],
        [209]], dtype=uint8),
 array([[158],
        [125],
        [134]], dtype=uint8),
 array([[104],
        [255],
        [255]], dtype=uint8),
 array([[121],
        [255],
        [ 97]], dtype=uint8),
 array([[143],
        [147],
        [182]], dtype=uint8)]